# Generated by Django 4.0.4 on 2022-06-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiDongDanhGia',
            fields=[
                ('Ma_HDDG', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Img_HDDG', models.ImageField(blank=True, null=True, upload_to='')),
                ('Password_HDDG', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ID_Khoa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Ten_Khoa', models.CharField(max_length=200)),
                ('SDT_Khoa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('Ma_Lop', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('SoLuong_SV', models.IntegerField()),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='PCD',
            fields=[
                ('Ma_PCD', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NgayLap_PCD', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('Ma_SV', models.IntegerField(primary_key=True, serialize=False)),
                ('Ten_SV', models.CharField(max_length=200)),
                ('NgaySinh_SV', models.DateField(blank=True, null=True)),
                ('SDT_SV', models.CharField(blank=True, max_length=10, null=True)),
                ('Email_SV', models.EmailField(blank=True, max_length=254, null=True)),
                ('DiaChi_SV', models.CharField(blank=True, max_length=200, null=True)),
                ('Password_SV', models.CharField(max_length=200)),
                ('GioiTinh_SV', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=200, null=True)),
                ('ChucVu_SV', models.CharField(choices=[('SV', 'SinhVien'), ('BCS', 'BanCanSu')], max_length=200)),
                ('Img_SV', models.ImageField(blank=True, null=True, upload_to='')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.lop')),
            ],
        ),
        migrations.CreateModel(
            name='CoVanHocTap',
            fields=[
                ('Ma_CVHT', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Ten_CVHT', models.CharField(blank=True, max_length=200, null=True)),
                ('SDT_CVHT', models.CharField(blank=True, max_length=10, null=True)),
                ('Email_CVHT', models.CharField(blank=True, max_length=200, null=True)),
                ('Password_CVHT', models.CharField(max_length=200)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.lop')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuDiem',
            fields=[
                ('Ma_CTPD', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('DiemTong_SV', models.IntegerField(blank=True, null=True)),
                ('MoTaDiem_SV', models.CharField(blank=True, max_length=1000, null=True)),
                ('XepLoai_SV', models.CharField(blank=True, max_length=200, null=True)),
                ('DiemTong_HDDG', models.IntegerField(blank=True, null=True)),
                ('MoTaDiem_HDDG', models.CharField(blank=True, max_length=1000, null=True)),
                ('XepLoai_HDDG', models.CharField(blank=True, max_length=200, null=True)),
                ('DiemTong_CVHT', models.IntegerField(blank=True, null=True)),
                ('MoTaDiem_CVHT', models.CharField(blank=True, max_length=1000, null=True)),
                ('XepLoai_CVHT', models.CharField(blank=True, max_length=200, null=True)),
                ('covanhoctap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.covanhoctap')),
                ('hoidongdanhgia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.hoidongdanhgia')),
                ('pcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.pcd')),
                ('sinhvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.sinhvien')),
            ],
        ),
    ]
