# Generated by Django 4.0.5 on 2022-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_hoidongdanhgia_khoa_lop_pcd_alter_greeting_when_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcd',
            name='DiemTong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcd',
            name='XepLoai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
