# Generated by Django 4.0.4 on 2022-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_upload_file_user_alter_greeting_when_data_thuattoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_thuattoan',
            name='Acc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_thuattoan',
            name='Gamma',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_thuattoan',
            name='Nu',
            field=models.FloatField(),
        ),
    ]
