# Generated by Django 4.0.5 on 2022-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_pcd_diemtong_pcd_xeploai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcd',
            name='HocKy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
