# Generated by Django 4.0.5 on 2022-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_pcd_hocky'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoiGianChamDiem',
            fields=[
                ('HocKy', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NgayBatDau', models.DateTimeField(blank=True, null=True)),
                ('NgayKetThuc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
